### ISSUE TITLE
Opening sources create huge trees of files

### ISSUE THREAD

**Issue by andreasdc** [eclipse-platform/.github#101]
When you try to get the source of the file, it opens the file from the referenced libraries, creating huge trees of packages and classes, instead of just redirecting you to the file from the workspace project.

**Comment by merks** [comment]
Please show a screen shot so we can understand what you see and what  you expect.

**Comment by andreasdc** [comment]
For example I have 1 project in my workspace. I use this project in the another one, and I click F3 to view the source. The "source" because it shows compiled something, opens from the referenced libraries, not from the workspace.

**Comment by merks** [comment]
Please show a screen shot.  It's very easy. You can simply copy the image (Snip & Sketch on Windows) and paste it into the entry field.

**Comment by andreasdc** [comment]
Screenshot of what? Referenced libraries?

**Comment by merks** [comment]
Yes, of this huge tree you are seeing in the IDE and what the open editor looks like.  I assume you have link-with-editor enabled, but a picture of your IDE is worth 1000 words of describing what you see in it.

**Comment by andreasdc** [comment]
It just opens the class inside the library from the referenced libraries.

**Comment by merks** [comment]
Less words, more pictures.

**Comment by andreasdc** [comment]
You don't know what referenced library look?
![image](https://user-images.githubusercontent.com/82218780/222900241-516b25e9-53f2-4e14-9a2d-65f37da4b422.png)

**Comment by merks** [comment]
Well, I expect it to look like this:

![image](https://user-images.githubusercontent.com/208716/222900389-226a6610-d01c-4885-a9dd-a0517b00e495.png)

But the "huge tree" only shows because I have link-with-editor (button underlined in red) enabled.    Presumably you do too, but I can't tell because it's not in your picture.  Also you can see that the editor that's opened is for a *.class file, but I can't tell in your case because that's also not part of your pictures.

But in my case there is no PropertyTest.java in the workspace.   So I'm wondering about your assertion that there is a workspace *.java file as opposed to only a *.class file from a library with attached source.  I'm a bit doubtful because workspace dependencies look like this:

![image](https://user-images.githubusercontent.com/208716/222900609-ada672d4-450e-4d95-ac9d-39c896e38a38.png)

They are not expandable so if you have a dependency on another project,  F3 will navigate to the project.

**Comment by andreasdc** [comment]
That's the issue. Link with editor button causes that. Thanks.
