### ISSUE TITLE
Flatpak version Bug

### ISSUE THREAD

**Issue by MatheusBrunheroto** [eclipse-platform/.github#175]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

Try to install any extension

I tried

Downloading other Linux, I was doing on Ubuntu and thought it might be a system glitch, so I downloaded
Debian and the exact same problem happened. but why did it happen at the first place? I don't know, all of a sudden
my IDE stopped working, and then i proceeded to reinstall it, then I couldn't install any extension at all.

I expected: No problems at all, just confirmation of terms and my extension.

But got: Cannot perform operation. Computing alternate solutions, may take a while n/15

## Here is some relevant log output

Cannot complete the install because one or more required items could not be found.
  Software being installed: Planet Themes 0.2.5.202202261537 (io.github.pyvesb.eclipse_planet_themes.feature.group 0.2.5.202202261537)
  Missing requirement: Planet Themes 0.2.5 (io.github.pyvesb.eclipse_planet_themes 0.2.5) requires 'osgi.bundle; javax.inject 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Planet Themes 0.2.5.202202261537 (io.github.pyvesb.eclipse_planet_themes.feature.group 0.2.5.202202261537)
    To: org.eclipse.equinox.p2.iu; io.github.pyvesb.eclipse_planet_themes [0.2.5,0.2.5]

## Tested under this environment:
* Ubuntu 22.04.3 and Debian 12
* Eclipse IDE/Platform version 4.30 (7 days ago)
* It happens with a lot of different extensions, because I obviously can't say all of them.

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by MatheusBrunheroto** [comment]
I outdated it to 4.29, works completely fine, other problem in 4.30 is, can't access browser via Eclipse -> help -> Eclipse user storage -> Open my Account

**Comment by akurtakov** [comment]
This is actually an issue that has to be fixed in https://github.com/PyvesB/eclipse-planet-themes . The following line (https://github.com/PyvesB/eclipse-planet-themes/blob/bce2b620edca65ef68cd47c3dc81294d0300fc82/planet-themes-plugin/META-INF/MANIFEST.MF#L16) goes against OSGi recomendation to use Package-Import and uses Require-Bundle. This binds to the third-party bundle name needlessly which upstream decided to change (see https://mvnrepository.com/artifact/javax.inject/javax.inject "moved to" box). Report the issue against eclipse-planet-themes to fix it instead as there is no way Eclipse Platform can guarantee BSN stability of third party code used in the project .
User storage is also a project that is not maintained as part of Eclipse Platform but it separate project with different set of maintainers - see details at https://projects.eclipse.org/projects/technology.usssdk/developer and report your user storage issue there.
I don't understand why you have Flatpak in the name as I haven't read anything flatpak specific in the details.
Anyway, all the actions are not actionable by this project thus I'm closing this issue.
