### ISSUE TITLE
No remedy found

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#185]
1. That popup is not helpful
![image](https://github.com/eclipse-platform/.github/assets/51790620/1ec54f69-2dc6-4814-a054-e2c38f359a86) 

2. that dialog is inappropriate unhelpfull: Details Area+the scrollbar is not visible so there is no hint what exactly went wrong:
![image](https://github.com/eclipse-platform/.github/assets/51790620/b3f39dbc-179e-4bf2-84be-d56ba7c99db3)

4. i just did a fresh OOmph of Platform only + pressed "Check for updates"=> error:

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: Eclipse Platform 4.31.0.v20240215-0947 (org.eclipse.platform.feature.group 4.31.0.v20240215-0947)
  Software currently installed: Eclipse IDE for Eclipse Committers 4.31.0.20240201-1200 (epp.package.committers 4.31.0.20240201-1200)
  Only one of the following can be installed at once: 
    Eclipse Platform 4.31.100.v20240127-1800 (org.eclipse.platform 4.31.100.v20240127-1800)
    Eclipse Platform 4.31.100.v20240213-1800 (org.eclipse.platform 4.31.100.v20240213-1800)
    Eclipse Platform 4.31.100.v20240215-0450 (org.eclipse.platform 4.31.100.v20240215-0450)
    Eclipse Platform 4.31.100.v20240214-1800 (org.eclipse.platform 4.31.100.v20240214-1800)
    Eclipse Platform 4.29.0.v20230903-1000 (org.eclipse.platform 4.29.0.v20230903-1000)
    Eclipse Platform 4.30.0.v20231201-0110 (org.eclipse.platform 4.30.0.v20231201-0110)
  Cannot satisfy dependency:
    From: Eclipse IDE for Eclipse Committers 4.31.0.20240201-1200 (epp.package.committers 4.31.0.20240201-1200)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.31.0.v20240127-1800,4.31.0.v20240127-1800]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.31.0.v20240127-1800 (org.eclipse.platform.feature.group 4.31.0.v20240127-1800)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform [4.31.100.v20240127-1800,4.31.100.v20240127-1800]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.31.0.v20240215-0947 (org.eclipse.platform.feature.group 4.31.0.v20240215-0947)
    To: org.eclipse.equinox.p2.iu; org.eclipse.platform [4.31.100.v20240215-0450,4.31.100.v20240215-0450]
```

@merks any idea?

**Comment by jukzi** [comment]
after a restart + pressed "Check for updates":
![image](https://github.com/eclipse-platform/.github/assets/51790620/01deecca-8b10-4c40-8832-6fe9b303dd8f)

**Comment by jukzi** [comment]
![image](https://github.com/eclipse-platform/.github/assets/51790620/3ff4d0f0-0dc4-4346-985b-2db55ac722f4)
do i understand right, oomph first installed 4.31.0.20240201-1200 and then updated to v20240215 automatically?

**Comment by merks** [comment]
The error mentions "Eclipse IDE for Eclipse Committers".  So does one of the pictures.  Another picture shows the Eclipse SDK.   You said you installed just the Platform from which I guess you mean the setup for it, but likely you installed into the Eclipse Committers package M2.  That's not such a good choice for the Platform's setup because you can't properly update that installation to the latest Platform SDK, like the project setup is hoping to be able to do.   So it feels a little like a scatter gun went off where it's not clean exactly what you did.   This should be the selection on first (product) page:

![image](https://github.com/eclipse-platform/.github/assets/208716/403e4fcf-3462-4b8b-96e8-12108c44e235)

**Comment by jukzi** [comment]
i tried that - because i am commiter:
![image](https://github.com/eclipse-platform/.github/assets/51790620/33f66a03-1521-4e62-a073-50414d9eb27c)

so "Package suited for development of Eclipse itself" is a lie?

**Comment by merks** [comment]
A damnable lie and someone should rot in hell for it.  😱 

The Committers package is the IDE that most committers use to develop their Eclipse Projects.  The Platform Project itself likes to eat its own dog food right off the assembly line rather than eating the Eclipse Packaging Project's dog food which has a much longer (and less frequent) update cycle.  The setup for the Platform projects are geared in that direction.  

You cannot update any EPP product to the latest SDK bundles and features because one of the requirements of `epp.package.committers` is like this:
```
    <required namespace='org.eclipse.equinox.p2.iu' name='org.eclipse.platform.feature.group' range='[4.31.0.v20240127-1800,4.31.0.v20240127-1800]'/>
```
So not being able to update is expected.

Generally using Help -> Perform Setup Tasks is the preferred way to do updates when you have an Oomph setup...
