### ISSUE TITLE
[installer] The engine operation was cancelled and the changes are being rolled back.

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/.github#28]
Today I tried to setup Egit: https://wiki.eclipse.org/EGit/Contributor_Guide#Automated_Developer_Setup

I updated the installer, and choose the "Eclipse IDE for Eclipse Committers" and then selected egit, after some downloading the installer tells me:

> The engine operation was cancelled and the changes are being rolled back.
> Took 3318 seconds.
> Task execution was canceled.
> Press Back to choose different settings or Cancel to abort.

I don't see any error or related message so I'm a bit stuck here, system is debian linux...

**Comment by mickaelistria** [comment]
The installer is not part of Eclipse Platform. It is provided by the Oomph project. Please report it to Oomph support channels.

**Comment by laeubi** [comment]
Do I need to download a new installer? Because I have already pressed the "update" button, or does it not work to update an "old" installer that way?

**Comment by merks** [comment]
It generally works to update, but there have been several occasions where the installer stops updating...  

The nightly installer should update to this, as seen in advanced mode on the bottom:

![image](https://user-images.githubusercontent.com/208716/175490167-63f1edc9-38e4-4de7-9898-36fdd3d9c261.png)

The regular installer should update to this:

![image](https://user-images.githubusercontent.com/208716/175490420-b36da774-e3ce-414f-bcba-6899c403ae7a.png)

**Comment by Bananeweizen** [comment]
If this occurs again, please try using the non-Oomph Help->Check for Updates. That one should show you the list of to be updated components and an error in the bottom half of the screen.
I have also experienced not being able to update installations with egit, and the root cause seems to be the removal of mylyn (but I'm not sure about it). Since egit depends on mylyn in the egit-github component, you may be able to get rid of mylyn and then to upgrade by uninstalling just egit-github, eventually. (I didn't try, creating another setup was faster...)

**Comment by merks** [comment]
Note though that this happened in the installer and not an IDE.

**Comment by Bananeweizen** [comment]
> Note though that this happened in the installer and not an IDE.

🤦🏻‍♂️ I should have been reading more carefully, must be the heat...
