### ISSUE TITLE
Eclipse silently crashes on startup

### ISSUE THREAD

**Issue by RichardGladman** [eclipse-platform/.github#47]
Eclipse: 2022-06
OS: Linux x86-64, Java 17

Plugins installed: None

This is a fresh install by extracting the tar.gz by which I mean I didn't use the installer

Steps to reproduce:
1. Run eclipse
2. Choose the default workspace
3. Click launch

Expected result:
Eclipse IDE opens and is usable

Actual result:
Eclipse IDE opens for a few seconds and then silently closes.

**Comment by merks** [comment]
The `<workspace>/.metadata/.log`  will likely exist and will likely contain helpful details that we'll need to understand the problem.  

Can you share the link of exactly what you downloaded?

**Comment by RichardGladman** [comment]
I downloaded from https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2022-06/R/eclipse-jee-2022-06-R-linux-gtk-x86_64.tar.gz

Also attached [log.txt](https://github.com/eclipse-platform/.github/files/9274964/log.txt)

**Comment by merks** [comment]
Thanks.   Unfortunately there is no helpful information there.  😞  Though given what's logged, it did get far enough to be processing all the extension registry contributions.

Maybe running with "eclipse -debug -consolelog 2>&1 | tee log" might help show information that's printed to std.out/std.err.  It seems to me on Linux that the GTK versions on the OS is often source of problems because SWT to "crash".

**Comment by RichardGladman** [comment]
Running the suggested command gives the following [log.txt](https://github.com/eclipse-platform/.github/files/9275020/log.txt)
.

**Comment by merks** [comment]
It all looks fine and normal.   Hopefully someone with more Linux experience will have an idea of what might be going wrong because it looks like it finished all the normal startup things and then there are literally no exceptions logged and no error messages printed.  I'm not sure the behavior on Linux when the JVM crashes, i.e., where the crash would be logged...

**Comment by HannesWell** [comment]
Can you check if the Eclipse process has terminated after the crash?
We recently discovered and fixed a deadlock in Equinox which ocoured with development versions of M2E. The secenario is different to yours but there it also looked like Eclipse had crashed, while it was actually just deadlocked after workspace selection without any UI Feedback.

**Comment by RichardGladman** [comment]
@merks Thanks for help anyway, it was an interesting poke around :)

@HannesWell It all looks OK with no obvious processes running.

**Comment by RichardGladman** [comment]
On the off-chance I rolled back last nights OS update and wouldn't you know it works now! I guess I'm reporting this in the wrong place.

**Comment by merks** [comment]
Thank you for the due diligence!

**Comment by sfPlayer1** [comment]
FYI this is most likely related to https://github.com/WebKit/WebKit/commit/a6277d4834cce0dea2f999d4c06ffa57abfbb82d
